### ISSUE TITLE
Upgrade to the latest Django 1.11

### ISSUE THREAD

**Issue by y4ahmed** [uva-slp/meals#224]
Upgrade Django from current version to latest version.

**Comment by AgentE382** [comment]
Upgraded on my dev box, and almost finished refactoring deprecated stuff so it passes all the tests. Do you think we need to refactor the stuff that will be deprecated in 2.0, or is that stuff fine to leave?

**Comment by y4ahmed** [comment]
Those should be fine to leave. That is a bit far ahead, not deprecated till
2019/2020(?), I think.

Cheers,
Yusuf Ahmed

**Comment by AgentE382** [comment]
Updated on the course server; @y4ahmed fixed the virtualenv. No current issues.
