### ISSUE TITLE
Read the legacy code to understand system

### ISSUE THREAD

**Issue by ces3uf** [uva-slp/meals#257]

**Comment by wyliew** [comment]
There's also a cron job on the server that runs createDailyReports every day, and I believe there's a basic email server? that's used for volunteers creating accounts (the initial email sent for their username / password). I'm not too sure about the email server, but i know something of that sort exists. 

(P.S. there's some good code practices like class-based views, and bad ones too like when we copied code for the different jobs, i.e., PackerJob and ShuttleRoute; we added them many months after we made Route so it was sloppily added. Sorry about that, but good luck with the project :+1: )

**Comment by rcdizon** [comment]
@uva-slp/meals Safe to say that we can close this? The documentation that we discovered last week should have helped us in addition to the work we've been doing across the past few iterations now.

**Comment by y4ahmed** [comment]
Closed, site documentation found and independent code review completed.
