### ISSUE TITLE
Make Sub Requests Searchable

### ISSUE THREAD

**Issue by ces3uf** [uva-slp/meals#321]
We need to fix the drop down of choosing people to sub for. It's not possible to type in the box and it's hard to find the people in the list since they're not always perfect alphabetized.

**Comment by rcdizon** [comment]
Mostly any dropdown in 'Volunteer Management'

**Comment by rcdizon** [comment]
Tougher than predicted, will push back to later iteration -- need to extend ModelForm to have dynamic search or alphabetized by first name (preferred more than last name)
